import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Shaunak Kulkarni' at '2/3/18 9:20 PM' with Gradle 2.14.1
 *
 * @author Shaunak Kulkarni, @date 2/3/18 9:20 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
