/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Shaunak Kulkarni' at '2/3/18 9:20 PM' with Gradle 2.14.1
 *
 * @author Shaunak Kulkarni, @date 2/3/18 9:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
